package com.assignment.tv9.model.DetailsOld

import com.assignment.tv9.model.Dashboard.DetailsExcerpt
import com.assignment.tv9.model.Dashboard.DetailsTitle
import com.google.gson.annotations.SerializedName

data class DetailsData(
    @SerializedName("id"                    ) var id                  : Int?           = null,
    @SerializedName("date"                  ) var date                : String?        = null,
    @SerializedName("date_gmt"              ) var dateGmt             : String?        = null,
    @SerializedName("modified"              ) var modified            : String?        = null,
    @SerializedName("modified_gmt"          ) var modifiedGmt         : String?        = null,
    @SerializedName("slug"                  ) var slug                : String?        = null,
    @SerializedName("status"                ) var status              : String?        = null,
    @SerializedName("type"                  ) var type                : String?        = null,
    @SerializedName("link"                  ) var link                : String?        = null,
    @SerializedName("title"                 ) var title               : DetailsTitle?         = DetailsTitle(),
    @SerializedName("short_headline"        ) var shortHeadline       : String?        = null,
    @SerializedName("category_name"         ) var categoryName        : String?        = null,
    @SerializedName("category_name_english" ) var categoryNameEnglish : String?        = null,
    @SerializedName("excerpt"               ) var excerpt             : DetailsExcerpt?       = DetailsExcerpt(),
    @SerializedName("author"                ) var author              : Int?           = null,
    @SerializedName("featured_media"        ) var featuredMedia       : Int?           = null,
    @SerializedName("comment_status"        ) var commentStatus       : String?        = null,
    @SerializedName("ping_status"           ) var pingStatus          : String?        = null,
    @SerializedName("format"                ) var format              : String?        = null,
    @SerializedName("categories"            ) var categories          : ArrayList<Int> = arrayListOf(),
    @SerializedName("web_featured_image"    ) var webFeaturedImage    : String?        = null,
    @SerializedName("mobile_featured_image" ) var mobileFeaturedImage : String?        = null,
    @SerializedName("gumlet_web_image"      ) var gumletWebImage      : String?        = null,
    @SerializedName("gumlet_mobile_image"   ) var gumletMobileImage   : String?        = null,
    @SerializedName("show_description"      ) var showDescription     : String?        = null,
    @SerializedName("content_url"           ) var contentUrl          : String?        = null,
    @SerializedName("has_video_post"        ) var hasVideoPost        : Boolean?       = null,
    @SerializedName("has_audio_post"        ) var hasAudioPost        : Boolean?       = null,
    @SerializedName("has_standard_post"     ) var hasStandardPost     : Boolean?       = null,
    @SerializedName("video_post_url"        ) var videoPostUrl        : String?        = null,
    @SerializedName("video_post_id"         ) var videoPostId         : String?        = null,
    @SerializedName("audio_post_url"        ) var audioPostUrl        : String?        = null,
    @SerializedName("audio_post_id"         ) var audioPostId         : String?        = null,
    @SerializedName("standard_post_url"     ) var standardPostUrl     : String?        = null,
    @SerializedName("standard_post_id"      ) var standardPostId      : String?        = null,
    @SerializedName("episode_no"            ) var episodeNo           : Int?           = null,
    @SerializedName("season_no"             ) var seasonNo            : Int?           = null,
    @SerializedName("show_type"             ) var showType            : String?        = null,
    @SerializedName("is_vidgyor"            ) var isVidgyor           : Boolean?       = null,
    @SerializedName("tags"                  ) var tags                : ArrayList<Int> = arrayListOf(),
    @SerializedName("_embedded"             ) var Embedded            : Embedded?      = Embedded(),
    @SerializedName("show_details"          ) var showDetails         : String?        = null)
